//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Database.Communication.DatabaseService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SecondNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CommentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Database.Communication.DatabaseService.Department CategoryField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Phone {
            get {
                return this.PhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneField, value) != true)) {
                    this.PhoneField = value;
                    this.RaisePropertyChanged("Phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SecondName {
            get {
                return this.SecondNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SecondNameField, value) != true)) {
                    this.SecondNameField = value;
                    this.RaisePropertyChanged("SecondName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public Database.Communication.DatabaseService.Department Category {
            get {
                return this.CategoryField;
            }
            set {
                if ((object.ReferenceEquals(this.CategoryField, value) != true)) {
                    this.CategoryField = value;
                    this.RaisePropertyChanged("Category");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Department", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Department : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartmentNameField;
        
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string DepartmentName {
            get {
                return this.DepartmentNameField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartmentNameField, value) != true)) {
                    this.DepartmentNameField = value;
                    this.RaisePropertyChanged("DepartmentName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DatabaseService.DatabaseServiceSoap")]
    public interface DatabaseServiceSoap {
        
        // CODEGEN: Контракт генерации сообщений с именем employee из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        Database.Communication.DatabaseService.AddResponse Add(Database.Communication.DatabaseService.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<Database.Communication.DatabaseService.AddResponse> AddAsync(Database.Communication.DatabaseService.AddRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем department из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DepatmentAdd", ReplyAction="*")]
        Database.Communication.DatabaseService.DepatmentAddResponse DepatmentAdd(Database.Communication.DatabaseService.DepatmentAddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DepatmentAdd", ReplyAction="*")]
        System.Threading.Tasks.Task<Database.Communication.DatabaseService.DepatmentAddResponse> DepatmentAddAsync(Database.Communication.DatabaseService.DepatmentAddRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем employee из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        Database.Communication.DatabaseService.UpdateResponse Update(Database.Communication.DatabaseService.UpdateRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Update", ReplyAction="*")]
        System.Threading.Tasks.Task<Database.Communication.DatabaseService.UpdateResponse> UpdateAsync(Database.Communication.DatabaseService.UpdateRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем employee из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Remove", ReplyAction="*")]
        Database.Communication.DatabaseService.RemoveResponse Remove(Database.Communication.DatabaseService.RemoveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Remove", ReplyAction="*")]
        System.Threading.Tasks.Task<Database.Communication.DatabaseService.RemoveResponse> RemoveAsync(Database.Communication.DatabaseService.RemoveRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем deparment из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DepartmenRemove", ReplyAction="*")]
        Database.Communication.DatabaseService.DepartmenRemoveResponse DepartmenRemove(Database.Communication.DatabaseService.DepartmenRemoveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DepartmenRemove", ReplyAction="*")]
        System.Threading.Tasks.Task<Database.Communication.DatabaseService.DepartmenRemoveResponse> DepartmenRemoveAsync(Database.Communication.DatabaseService.DepartmenRemoveRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем LoadDepartmensResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadDepartmens", ReplyAction="*")]
        Database.Communication.DatabaseService.LoadDepartmensResponse LoadDepartmens(Database.Communication.DatabaseService.LoadDepartmensRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadDepartmens", ReplyAction="*")]
        System.Threading.Tasks.Task<Database.Communication.DatabaseService.LoadDepartmensResponse> LoadDepartmensAsync(Database.Communication.DatabaseService.LoadDepartmensRequest request);
        
        // CODEGEN: Контракт генерации сообщений с именем LoadEmployeesResult из пространства имен http://tempuri.org/ не отмечен как обнуляемый
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadEmployees", ReplyAction="*")]
        Database.Communication.DatabaseService.LoadEmployeesResponse LoadEmployees(Database.Communication.DatabaseService.LoadEmployeesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LoadEmployees", ReplyAction="*")]
        System.Threading.Tasks.Task<Database.Communication.DatabaseService.LoadEmployeesResponse> LoadEmployeesAsync(Database.Communication.DatabaseService.LoadEmployeesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Add", Namespace="http://tempuri.org/", Order=0)]
        public Database.Communication.DatabaseService.AddRequestBody Body;
        
        public AddRequest() {
        }
        
        public AddRequest(Database.Communication.DatabaseService.AddRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Database.Communication.DatabaseService.Employee employee;
        
        public AddRequestBody() {
        }
        
        public AddRequestBody(Database.Communication.DatabaseService.Employee employee) {
            this.employee = employee;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddResponse", Namespace="http://tempuri.org/", Order=0)]
        public Database.Communication.DatabaseService.AddResponseBody Body;
        
        public AddResponse() {
        }
        
        public AddResponse(Database.Communication.DatabaseService.AddResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int AddResult;
        
        public AddResponseBody() {
        }
        
        public AddResponseBody(int AddResult) {
            this.AddResult = AddResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DepatmentAddRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DepatmentAdd", Namespace="http://tempuri.org/", Order=0)]
        public Database.Communication.DatabaseService.DepatmentAddRequestBody Body;
        
        public DepatmentAddRequest() {
        }
        
        public DepatmentAddRequest(Database.Communication.DatabaseService.DepatmentAddRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DepatmentAddRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Database.Communication.DatabaseService.Department department;
        
        public DepatmentAddRequestBody() {
        }
        
        public DepatmentAddRequestBody(Database.Communication.DatabaseService.Department department) {
            this.department = department;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DepatmentAddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DepatmentAddResponse", Namespace="http://tempuri.org/", Order=0)]
        public Database.Communication.DatabaseService.DepatmentAddResponseBody Body;
        
        public DepatmentAddResponse() {
        }
        
        public DepatmentAddResponse(Database.Communication.DatabaseService.DepatmentAddResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DepatmentAddResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int DepatmentAddResult;
        
        public DepatmentAddResponseBody() {
        }
        
        public DepatmentAddResponseBody(int DepatmentAddResult) {
            this.DepatmentAddResult = DepatmentAddResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Update", Namespace="http://tempuri.org/", Order=0)]
        public Database.Communication.DatabaseService.UpdateRequestBody Body;
        
        public UpdateRequest() {
        }
        
        public UpdateRequest(Database.Communication.DatabaseService.UpdateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Database.Communication.DatabaseService.Employee employee;
        
        public UpdateRequestBody() {
        }
        
        public UpdateRequestBody(Database.Communication.DatabaseService.Employee employee) {
            this.employee = employee;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateResponse", Namespace="http://tempuri.org/", Order=0)]
        public Database.Communication.DatabaseService.UpdateResponseBody Body;
        
        public UpdateResponse() {
        }
        
        public UpdateResponse(Database.Communication.DatabaseService.UpdateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int UpdateResult;
        
        public UpdateResponseBody() {
        }
        
        public UpdateResponseBody(int UpdateResult) {
            this.UpdateResult = UpdateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Remove", Namespace="http://tempuri.org/", Order=0)]
        public Database.Communication.DatabaseService.RemoveRequestBody Body;
        
        public RemoveRequest() {
        }
        
        public RemoveRequest(Database.Communication.DatabaseService.RemoveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemoveRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Database.Communication.DatabaseService.Employee employee;
        
        public RemoveRequestBody() {
        }
        
        public RemoveRequestBody(Database.Communication.DatabaseService.Employee employee) {
            this.employee = employee;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveResponse", Namespace="http://tempuri.org/", Order=0)]
        public Database.Communication.DatabaseService.RemoveResponseBody Body;
        
        public RemoveResponse() {
        }
        
        public RemoveResponse(Database.Communication.DatabaseService.RemoveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RemoveResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int RemoveResult;
        
        public RemoveResponseBody() {
        }
        
        public RemoveResponseBody(int RemoveResult) {
            this.RemoveResult = RemoveResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DepartmenRemoveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DepartmenRemove", Namespace="http://tempuri.org/", Order=0)]
        public Database.Communication.DatabaseService.DepartmenRemoveRequestBody Body;
        
        public DepartmenRemoveRequest() {
        }
        
        public DepartmenRemoveRequest(Database.Communication.DatabaseService.DepartmenRemoveRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DepartmenRemoveRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Database.Communication.DatabaseService.Department deparment;
        
        public DepartmenRemoveRequestBody() {
        }
        
        public DepartmenRemoveRequestBody(Database.Communication.DatabaseService.Department deparment) {
            this.deparment = deparment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DepartmenRemoveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DepartmenRemoveResponse", Namespace="http://tempuri.org/", Order=0)]
        public Database.Communication.DatabaseService.DepartmenRemoveResponseBody Body;
        
        public DepartmenRemoveResponse() {
        }
        
        public DepartmenRemoveResponse(Database.Communication.DatabaseService.DepartmenRemoveResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DepartmenRemoveResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int DepartmenRemoveResult;
        
        public DepartmenRemoveResponseBody() {
        }
        
        public DepartmenRemoveResponseBody(int DepartmenRemoveResult) {
            this.DepartmenRemoveResult = DepartmenRemoveResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadDepartmensRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadDepartmens", Namespace="http://tempuri.org/", Order=0)]
        public Database.Communication.DatabaseService.LoadDepartmensRequestBody Body;
        
        public LoadDepartmensRequest() {
        }
        
        public LoadDepartmensRequest(Database.Communication.DatabaseService.LoadDepartmensRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LoadDepartmensRequestBody {
        
        public LoadDepartmensRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadDepartmensResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadDepartmensResponse", Namespace="http://tempuri.org/", Order=0)]
        public Database.Communication.DatabaseService.LoadDepartmensResponseBody Body;
        
        public LoadDepartmensResponse() {
        }
        
        public LoadDepartmensResponse(Database.Communication.DatabaseService.LoadDepartmensResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoadDepartmensResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Database.Communication.DatabaseService.Department[] LoadDepartmensResult;
        
        public LoadDepartmensResponseBody() {
        }
        
        public LoadDepartmensResponseBody(Database.Communication.DatabaseService.Department[] LoadDepartmensResult) {
            this.LoadDepartmensResult = LoadDepartmensResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadEmployeesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadEmployees", Namespace="http://tempuri.org/", Order=0)]
        public Database.Communication.DatabaseService.LoadEmployeesRequestBody Body;
        
        public LoadEmployeesRequest() {
        }
        
        public LoadEmployeesRequest(Database.Communication.DatabaseService.LoadEmployeesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class LoadEmployeesRequestBody {
        
        public LoadEmployeesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoadEmployeesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoadEmployeesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Database.Communication.DatabaseService.LoadEmployeesResponseBody Body;
        
        public LoadEmployeesResponse() {
        }
        
        public LoadEmployeesResponse(Database.Communication.DatabaseService.LoadEmployeesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoadEmployeesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Database.Communication.DatabaseService.Employee[] LoadEmployeesResult;
        
        public LoadEmployeesResponseBody() {
        }
        
        public LoadEmployeesResponseBody(Database.Communication.DatabaseService.Employee[] LoadEmployeesResult) {
            this.LoadEmployeesResult = LoadEmployeesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DatabaseServiceSoapChannel : Database.Communication.DatabaseService.DatabaseServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DatabaseServiceSoapClient : System.ServiceModel.ClientBase<Database.Communication.DatabaseService.DatabaseServiceSoap>, Database.Communication.DatabaseService.DatabaseServiceSoap {
        
        public DatabaseServiceSoapClient() {
        }
        
        public DatabaseServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DatabaseServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatabaseServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DatabaseServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Database.Communication.DatabaseService.AddResponse Database.Communication.DatabaseService.DatabaseServiceSoap.Add(Database.Communication.DatabaseService.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public int Add(Database.Communication.DatabaseService.Employee employee) {
            Database.Communication.DatabaseService.AddRequest inValue = new Database.Communication.DatabaseService.AddRequest();
            inValue.Body = new Database.Communication.DatabaseService.AddRequestBody();
            inValue.Body.employee = employee;
            Database.Communication.DatabaseService.AddResponse retVal = ((Database.Communication.DatabaseService.DatabaseServiceSoap)(this)).Add(inValue);
            return retVal.Body.AddResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Database.Communication.DatabaseService.AddResponse> Database.Communication.DatabaseService.DatabaseServiceSoap.AddAsync(Database.Communication.DatabaseService.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public System.Threading.Tasks.Task<Database.Communication.DatabaseService.AddResponse> AddAsync(Database.Communication.DatabaseService.Employee employee) {
            Database.Communication.DatabaseService.AddRequest inValue = new Database.Communication.DatabaseService.AddRequest();
            inValue.Body = new Database.Communication.DatabaseService.AddRequestBody();
            inValue.Body.employee = employee;
            return ((Database.Communication.DatabaseService.DatabaseServiceSoap)(this)).AddAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Database.Communication.DatabaseService.DepatmentAddResponse Database.Communication.DatabaseService.DatabaseServiceSoap.DepatmentAdd(Database.Communication.DatabaseService.DepatmentAddRequest request) {
            return base.Channel.DepatmentAdd(request);
        }
        
        public int DepatmentAdd(Database.Communication.DatabaseService.Department department) {
            Database.Communication.DatabaseService.DepatmentAddRequest inValue = new Database.Communication.DatabaseService.DepatmentAddRequest();
            inValue.Body = new Database.Communication.DatabaseService.DepatmentAddRequestBody();
            inValue.Body.department = department;
            Database.Communication.DatabaseService.DepatmentAddResponse retVal = ((Database.Communication.DatabaseService.DatabaseServiceSoap)(this)).DepatmentAdd(inValue);
            return retVal.Body.DepatmentAddResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Database.Communication.DatabaseService.DepatmentAddResponse> Database.Communication.DatabaseService.DatabaseServiceSoap.DepatmentAddAsync(Database.Communication.DatabaseService.DepatmentAddRequest request) {
            return base.Channel.DepatmentAddAsync(request);
        }
        
        public System.Threading.Tasks.Task<Database.Communication.DatabaseService.DepatmentAddResponse> DepatmentAddAsync(Database.Communication.DatabaseService.Department department) {
            Database.Communication.DatabaseService.DepatmentAddRequest inValue = new Database.Communication.DatabaseService.DepatmentAddRequest();
            inValue.Body = new Database.Communication.DatabaseService.DepatmentAddRequestBody();
            inValue.Body.department = department;
            return ((Database.Communication.DatabaseService.DatabaseServiceSoap)(this)).DepatmentAddAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Database.Communication.DatabaseService.UpdateResponse Database.Communication.DatabaseService.DatabaseServiceSoap.Update(Database.Communication.DatabaseService.UpdateRequest request) {
            return base.Channel.Update(request);
        }
        
        public int Update(Database.Communication.DatabaseService.Employee employee) {
            Database.Communication.DatabaseService.UpdateRequest inValue = new Database.Communication.DatabaseService.UpdateRequest();
            inValue.Body = new Database.Communication.DatabaseService.UpdateRequestBody();
            inValue.Body.employee = employee;
            Database.Communication.DatabaseService.UpdateResponse retVal = ((Database.Communication.DatabaseService.DatabaseServiceSoap)(this)).Update(inValue);
            return retVal.Body.UpdateResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Database.Communication.DatabaseService.UpdateResponse> Database.Communication.DatabaseService.DatabaseServiceSoap.UpdateAsync(Database.Communication.DatabaseService.UpdateRequest request) {
            return base.Channel.UpdateAsync(request);
        }
        
        public System.Threading.Tasks.Task<Database.Communication.DatabaseService.UpdateResponse> UpdateAsync(Database.Communication.DatabaseService.Employee employee) {
            Database.Communication.DatabaseService.UpdateRequest inValue = new Database.Communication.DatabaseService.UpdateRequest();
            inValue.Body = new Database.Communication.DatabaseService.UpdateRequestBody();
            inValue.Body.employee = employee;
            return ((Database.Communication.DatabaseService.DatabaseServiceSoap)(this)).UpdateAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Database.Communication.DatabaseService.RemoveResponse Database.Communication.DatabaseService.DatabaseServiceSoap.Remove(Database.Communication.DatabaseService.RemoveRequest request) {
            return base.Channel.Remove(request);
        }
        
        public int Remove(Database.Communication.DatabaseService.Employee employee) {
            Database.Communication.DatabaseService.RemoveRequest inValue = new Database.Communication.DatabaseService.RemoveRequest();
            inValue.Body = new Database.Communication.DatabaseService.RemoveRequestBody();
            inValue.Body.employee = employee;
            Database.Communication.DatabaseService.RemoveResponse retVal = ((Database.Communication.DatabaseService.DatabaseServiceSoap)(this)).Remove(inValue);
            return retVal.Body.RemoveResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Database.Communication.DatabaseService.RemoveResponse> Database.Communication.DatabaseService.DatabaseServiceSoap.RemoveAsync(Database.Communication.DatabaseService.RemoveRequest request) {
            return base.Channel.RemoveAsync(request);
        }
        
        public System.Threading.Tasks.Task<Database.Communication.DatabaseService.RemoveResponse> RemoveAsync(Database.Communication.DatabaseService.Employee employee) {
            Database.Communication.DatabaseService.RemoveRequest inValue = new Database.Communication.DatabaseService.RemoveRequest();
            inValue.Body = new Database.Communication.DatabaseService.RemoveRequestBody();
            inValue.Body.employee = employee;
            return ((Database.Communication.DatabaseService.DatabaseServiceSoap)(this)).RemoveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Database.Communication.DatabaseService.DepartmenRemoveResponse Database.Communication.DatabaseService.DatabaseServiceSoap.DepartmenRemove(Database.Communication.DatabaseService.DepartmenRemoveRequest request) {
            return base.Channel.DepartmenRemove(request);
        }
        
        public int DepartmenRemove(Database.Communication.DatabaseService.Department deparment) {
            Database.Communication.DatabaseService.DepartmenRemoveRequest inValue = new Database.Communication.DatabaseService.DepartmenRemoveRequest();
            inValue.Body = new Database.Communication.DatabaseService.DepartmenRemoveRequestBody();
            inValue.Body.deparment = deparment;
            Database.Communication.DatabaseService.DepartmenRemoveResponse retVal = ((Database.Communication.DatabaseService.DatabaseServiceSoap)(this)).DepartmenRemove(inValue);
            return retVal.Body.DepartmenRemoveResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Database.Communication.DatabaseService.DepartmenRemoveResponse> Database.Communication.DatabaseService.DatabaseServiceSoap.DepartmenRemoveAsync(Database.Communication.DatabaseService.DepartmenRemoveRequest request) {
            return base.Channel.DepartmenRemoveAsync(request);
        }
        
        public System.Threading.Tasks.Task<Database.Communication.DatabaseService.DepartmenRemoveResponse> DepartmenRemoveAsync(Database.Communication.DatabaseService.Department deparment) {
            Database.Communication.DatabaseService.DepartmenRemoveRequest inValue = new Database.Communication.DatabaseService.DepartmenRemoveRequest();
            inValue.Body = new Database.Communication.DatabaseService.DepartmenRemoveRequestBody();
            inValue.Body.deparment = deparment;
            return ((Database.Communication.DatabaseService.DatabaseServiceSoap)(this)).DepartmenRemoveAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Database.Communication.DatabaseService.LoadDepartmensResponse Database.Communication.DatabaseService.DatabaseServiceSoap.LoadDepartmens(Database.Communication.DatabaseService.LoadDepartmensRequest request) {
            return base.Channel.LoadDepartmens(request);
        }
        
        public Database.Communication.DatabaseService.Department[] LoadDepartmens() {
            Database.Communication.DatabaseService.LoadDepartmensRequest inValue = new Database.Communication.DatabaseService.LoadDepartmensRequest();
            inValue.Body = new Database.Communication.DatabaseService.LoadDepartmensRequestBody();
            Database.Communication.DatabaseService.LoadDepartmensResponse retVal = ((Database.Communication.DatabaseService.DatabaseServiceSoap)(this)).LoadDepartmens(inValue);
            return retVal.Body.LoadDepartmensResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Database.Communication.DatabaseService.LoadDepartmensResponse> Database.Communication.DatabaseService.DatabaseServiceSoap.LoadDepartmensAsync(Database.Communication.DatabaseService.LoadDepartmensRequest request) {
            return base.Channel.LoadDepartmensAsync(request);
        }
        
        public System.Threading.Tasks.Task<Database.Communication.DatabaseService.LoadDepartmensResponse> LoadDepartmensAsync() {
            Database.Communication.DatabaseService.LoadDepartmensRequest inValue = new Database.Communication.DatabaseService.LoadDepartmensRequest();
            inValue.Body = new Database.Communication.DatabaseService.LoadDepartmensRequestBody();
            return ((Database.Communication.DatabaseService.DatabaseServiceSoap)(this)).LoadDepartmensAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Database.Communication.DatabaseService.LoadEmployeesResponse Database.Communication.DatabaseService.DatabaseServiceSoap.LoadEmployees(Database.Communication.DatabaseService.LoadEmployeesRequest request) {
            return base.Channel.LoadEmployees(request);
        }
        
        public Database.Communication.DatabaseService.Employee[] LoadEmployees() {
            Database.Communication.DatabaseService.LoadEmployeesRequest inValue = new Database.Communication.DatabaseService.LoadEmployeesRequest();
            inValue.Body = new Database.Communication.DatabaseService.LoadEmployeesRequestBody();
            Database.Communication.DatabaseService.LoadEmployeesResponse retVal = ((Database.Communication.DatabaseService.DatabaseServiceSoap)(this)).LoadEmployees(inValue);
            return retVal.Body.LoadEmployeesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Database.Communication.DatabaseService.LoadEmployeesResponse> Database.Communication.DatabaseService.DatabaseServiceSoap.LoadEmployeesAsync(Database.Communication.DatabaseService.LoadEmployeesRequest request) {
            return base.Channel.LoadEmployeesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Database.Communication.DatabaseService.LoadEmployeesResponse> LoadEmployeesAsync() {
            Database.Communication.DatabaseService.LoadEmployeesRequest inValue = new Database.Communication.DatabaseService.LoadEmployeesRequest();
            inValue.Body = new Database.Communication.DatabaseService.LoadEmployeesRequestBody();
            return ((Database.Communication.DatabaseService.DatabaseServiceSoap)(this)).LoadEmployeesAsync(inValue);
        }
    }
}
